title: "Union of Grinnell Student Dining Workers"
description: "The only independent undergraduate labor union in the country, UGSDW fights for fair pay and benefits for workers at Grinnell College."
url: "https://www.ugsdw.org"

permalink: pretty

include:
    - _pages

defaults:
    - scope:
        path: ""
      values:
        layout: default

    - scope:
        path: ""
        type: posts
      values:
        layout: post
        subtitle: 
    
    - scope:
        path: "_pages"
        type: "pages"
      values:
        layout: page

sass:
    style: compressed
    sass_dir: ./css

plugins:
    - jekyll-sitemap
    - jekyll-liquify