backend:
  name: git-gateway
  branch: master # Branch to update (master by default)

media_folder: "assets/uploads" # Folder where user uploaded files should go

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Posts (News & Press)" # Used in the UI, ie.: "New Post"
    folder: "_posts/" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor: 
      preview: false
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Subtitle", name: "subtitle", widget: "markdown", required: false}
      - {label: "Author", name: "author", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "page"
    label: "Pages"
    folder: "_pages/"
    label_singluar: "Page"
    create: true
    editor: 
      preview: false
    fields: 
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Link", name: "permalink", widget: "string" }
      - { label: "Include Sidebar", name: "nosidebar", widget: "boolean", default: true, required: false}
      - { label: "CSS", name: "css", widget: "hidden", default: "news-wrapper"}
      - label: "Page Contents"
        name: "contents"
        widget: "list"
        types:
          - label: "Text Field"
            name: "text"
            widget: "object"
            fields:
              - { label: "Text", name: "text", widget: "markdown" }
          - label: "Line Break"
            name: "break"
            fields:
              - { label: "Placeholder", name: "ph", widget: "hidden"}
          - label: "Press Release Tagline"
            name: "press-release"
            fields: 
              - { label: "Placeholder", name: "ph", widget: "hidden"}
          - label: "Button"
            name: "button"
            widget: "object"
            fields:
              - { label: "Gold Button", name: "gold", widget: "boolean", default: false, required: false }
              - { label: "Link", name: "link", widget: "string" }
              - { label: "Text", name: "text", widget: "string" }
          - label: "PDF"
            name: "pdf"
            fields:
              - { label: "Link", name: "link", widget: "string" }
              - { label: "Size", name: "size", widget: "number", default: 800 }
          - label: "News Section"
            name: "news"
            fields:
              - { label: "Max # of Articles to Show", name: "limit", widget: "number" }
              - { label: "Archive Options", name: "archive-filter", widget: "string", hint: "Use all, archive-only, or recent-only (case sensitive)." }
  - name: "config"
    label: "Data Configuration"
    editor:
      preview: false
    files:
      - label: "Sidebar"
        name: "sidebar"
        file: "_data/sidebar.yml"
        fields:
          - { label: "Text", name: "text", widget: "string" }
          label: "Buttons"
                name: "buttons"
                widget: 'list'
                fields:
                  - { label: "Accented Button", name: "accent", widget: "boolean", required: false, default: false }
                  - { label: "Name", name: "name", widget: "string", pattern: ['^(.|\n){0,54}$', "Maximum 54 characters"] }
                  - { label: "Link", name: "link", widget: "string" }
      - label: "Home Page"
        name: "home"
        file: "_data/home.yml"
        fields:
          - label: "Banner"
            name: "banner"
            widget: "object"
            summary: "{{fields.text}}"
            collapsed: true
            fields:
              - { label: "Image", name: "image", widget: "image", allow_multiple: false }
              - { label: "Text", name: "text", widget: "string" }
              - label: "Buttons"
                name: "buttons"
                widget: 'list'
                hint: "It is highly reccommended to keep this between 1-3 buttons. No more than 4!"
                fields:
                  - { label: "Accented Button", name: "accent", widget: "boolean", required: false, default: false }
                  - { label: "Name", name: "name", widget: "string", pattern: ['^(.|\n){0,12}$', "Maximum 12 characters"] }
                  - { label: "Link", name: "link", widget: "string" }
          - label: "News Section"
            name: "news"
            widget: "object"
            collapsed: true
            fields:
              - { label: "Text", name: "text", widget: "string" }
              - { label: "Maximum Displayed Articles", name: "max-articles", widget: "number", default: 5, vaule_type: "int", min: 1, max: 20 }
              - label: "Buttons"
                name: "buttons"
                widget: 'list'
                fields:
                  - { label: "Name", name: "name", widget: "string", pattern: ['^(.|\n){0,23}$', "Maximum 23 characters"] }
                  - { label: "Link", name: "link", widget: "string" }
          - label: "Benefits Section"
            name: "benefits"
            widget: "list"
            collapsed: true
            hint: "It is highly reccommended to keep this at 6 items. Make sure the formatting looks good on both desktops and phones!"
            types:
              - label: "Big Text Item"
                name: "big"
                widget: "object"
                summary: "{{fields.big-text}}"
                fields:
                  - { label: "Big Text", name: "big-text", pattern: ['^(.|\n){0,6}$', "Maximum 6 characters"], hint: "5 character max, 6 with a period." }
                  - { label: "Subtext", name: "subtext", pattern: ['^(.|\n){0,33}$', "Maximum 33 characters"] }
              - label: "Medium Text Item"
                name: "medium"
                widget: "object"
                summary: "{{fields.big-text}}"
                fields:
                  - { label: "Big Text", name: "big-text", pattern: ['^(.|\n){0,11}$', "Maximum 11 characters"] }
                  - { label: "Subtext", name: "subtext", pattern: ['^(.|\n){0,70}$', "Maximum 70 characters"] }
              - label: "Small Text Item"
                name: "small"
                widget: "object"
                summary: "{{fields.text}}"
                fields:
                  - { label: "Text", name: "text", pattern: ['^(.|\n){0,150}$', "Maximum 150 characters"] }
          - label: "Join Section"
            name: "join"
            widget: "object"
            collapsed: true
            fields:
              - { label: "Number of registered members", name: "member-count", widget: "number", vaule_type: "int", min: 0 }
              - { label: "Button Link", name: "button-link", widget: "string" }
          - label: "Resources Section"
            name: "resources"
            widget: "list"
            collapsed: true
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Link", name: "link", widget: "string" }
      - label: "Current Site Data - UPDATE REGULARLY!"
        name: "global"
        file: "_data/global.yml"
        fields:
          - { label: "Press Release Tagline", name: "press-release-tag", widget: "markdown" }
          - { label: "Archival Date for Posts", name: "archive-date", widget: "number", hint: "posts at and beyond this date will be archived. PLEASE use yyyyMMdd format EXPLICITLY (or this will break)!", pattern: ['(?<!\d)(?:(?:20\d{2})(?:(?:(?:0[13578]|1[02])31)|(?:(?:0[1,3-9]|1[0-2])(?:29|30)))|(?:(?:20(?:0[48]|[2468][048]|[13579][26]))0229)|(?:20\d{2})(?:(?:0?[1-9])|(?:1[0-2]))(?:0?[1-9]|1\d|2[0-8]))(?!\d)', "Make sure you are using the correct format."] } # yes, this is a regex pattern. yes, it is insane. if it doesnt work feel free to delete it.
          - label: "UGSDW President"
            name: "president"
            widget: "object"
            summary: "{{fields.name}}"
            collapsed: true
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Email", name: "email", widget: "string" }
          - label: "UGSDW Secretary-Treasurer"
            name: "sec-treas"
            widget: "object"
            summary: "{{fields.name}}"
            collapsed: true
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Email", name: "email", widget: "string" }
          - label: "UGSDW Members At-Large"
            name: "at-large"
            widget: "list"
            collapsed: true
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Email", name: "email", widget: "string" }
          - label: "UGSDW Press Secretary"
            name: "press-secretary"
            widget: "object"
            summary: "{{fields.name}}"
            collapsed: true
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Email", name: "email", widget: "string" }
          - label: "UGSDW Advisors"
            name: "advisors"
            widget: "list"
            collapsed: true
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Email", name: "email", widget: "string" }
      - label: "Navigation Bar"
        name: "navigation"
        file: "_data/navigation.yml"
        fields:
          - label: "Far-left Navigation Button"
            name: "left-end-button"
            widget: "object"
            summary: "{{fields.name}}"
            collapsed: true
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Link", name: "link", widget: "string", required: false }
              - label: "Contents"
                name: "contents"
                widget: 'list'
                fields:
                  - { label: Name, name: name, widget: string }
                  - { label: Link, name: link, widget: string }
          - label: "Center-left Navigation Button"
            name: "left-center-button"
            widget: "object"
            summary: "{{fields.name}}"
            collapsed: true
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Link", name: "link", widget: "string", required: false }
              - label: "Contents"
                name: "contents"
                widget: 'list'
                fields:
                  - { label: Name, name: name, widget: string }
                  - { label: Link, name: link, widget: string }
          - label: "Center-right Navigation Button"
            name: "right-center-button"
            widget: "object"
            summary: "{{fields.name}}"
            collapsed: true
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Link", name: "link", widget: "string", required: false }
              - label: "Contents"
                name: "contents"
                widget: 'list'
                fields:
                  - { label: Name, name: name, widget: string }
                  - { label: Link, name: link, widget: string }
          - label: "Far-right Navigation Button"
            name: "right-end-button"
            widget: "object"
            summary: "{{fields.name}}"
            collapsed: true
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Link", name: "link", widget: "string" }