backend:
  name: git-gateway
  branch: master # Branch to update (master by default)

media_folder: "assets/uploads" # Folder where user uploaded files should go

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Posts - News & Press" # Used in the UI, ie.: "New Post"
    folder: "_posts/" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor: 
      preview: false
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Categories", name: "categories", widget: "string", required: false}
  - name: "config"
    label: "Data Configuration"
    editor:
      preview: false
    files:
      - label: "Home Page Configuration"
        name: "home"
        file: "_data/home.yml"
        fields:
          - label: "Banner"
            name: "banner"
            widget: "object"
            summary: "{{fields.text}}"
            collapsed: true
            fields:
              - { label: "Image", name: "image", widget: "image", allow_multiple: false }
              - { label: "Text", name: "text", widget: "string" }
              - label: "Buttons"
                name: "buttons"
                widget: 'list'
                fields:
                  - { label: "Accented Button", name: "accent", widget: "boolean" }
                  - { label: "Name", name: "name", widget: "string" }
                  - { label: "Link", name: "link", widget: "string" }
          - label: "News Section"
            name: "news"
            widget: "object"
            collapsed: true
            fields:
              - { label: "Text", name: "text", widget: "string" }
              - { label: "Maximum Displayed Articles", name: "max-articles", widget: "number", default: 5, vaule_type: "int", min: 1, max: 20 }
          - label: "Benefits Section"
            name: "benefits"
            widget: "list"
            collapsed: true
            types:
              - label: "Big Text Item"
                name: "big"
                widget: "object"
                summary: "{{fields.big-text}}"
                fields:
                  - { label: "Big Text", name: "big-text", pattern: ['^(.|\n){0,6}$', "Must have less than 7 characters"] }
                  - { label: "Subtext", name: "subtext", pattern: ['^(.|\n){0,40}$', "Must have less than 41 characters"] }
              - label: "Medium Text Item"
                name: "medium"
                widget: "object"
                summary: "{{fields.big-text}}"
                fields:
                  - { label: "Big Text", name: "big-text", pattern: ['^(.|\n){0,6}$', "Must have less than 7 characters"] }
                  - { label: "Subtext", name: "subtext", pattern: ['^(.|\n){0,40}$', "Must have less than 41 characters"] }
              - label: "Small Text Item"
                name: "small"
                widget: "object"
                summary: "{{fields.text}}"
                fields:
                  - { label: "Text", name: "text", pattern: ['^(.|\n){0,150}$', "Must have less than 151 characters"] }
          - label: "Join Section"
            name: "join"
            widget: "object"
            collapsed: true
            fields:
              - { label: "Number of registered members", name: "member-count", widget: "number", vaule_type: "int", min: 0 }
              - { label: "Button Link", name: "button-link", widget: "string" }
          - label: "Resources Section"
            name: "resources"
            widget: "list"
            collapsed: true
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Link", name: "link", widget: "string" }
      - label: "Current UGSDW Officers - update regularly"
        name: "officers"
        file: "_data/officers.yml"
        fields:
          - label: "UGSDW President"
            name: "president"
            widget: "object"
            summary: "{{fields.name}}"
            collapsed: true
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Email", name: "email", widget: "string" }
          - label: "UGSDW Secretary-Treasurer"
            name: "sec-treas"
            widget: "object"
            summary: "{{fields.name}}"
            collapsed: true
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Email", name: "email", widget: "string" }
          - label: "UGSDW Members At-Large"
            name: "at-large"
            widget: "list"
            collapsed: true
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Email", name: "email", widget: "string" }
          - label: "UGSDW Press Secretary"
            name: "press-secretary"
            widget: "object"
            summary: "{{fields.name}}"
            collapsed: true
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Email", name: "email", widget: "string" }
          - label: "UGSDW Advisors"
            name: "advisors"
            widget: "list"
            collapsed: true
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Email", name: "email", widget: "string" }
      - label: "Navigation Bar - do not change without care!"
        name: "navigation"
        file: "_data/navigation.yml"
        fields:
          - label: "Far-left Navigation Button"
            name: "left-end-button"
            widget: "object"
            summary: "{{fields.name}}"
            collapsed: true
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Link", name: "link", widget: "string", required: false }
              - label: "Contents"
                name: "contents"
                widget: 'list'
                fields:
                  - { label: Name, name: name, widget: string }
                  - { label: Link, name: link, widget: string }
          - label: "Center-left Navigation Button"
            name: "left-center-button"
            widget: "object"
            summary: "{{fields.name}}"
            collapsed: true
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Link", name: "link", widget: "string", required: false }
              - label: "Contents"
                name: "contents"
                widget: 'list'
                fields:
                  - { label: Name, name: name, widget: string }
                  - { label: Link, name: link, widget: string }
          - label: "Center-right Navigation Button"
            name: "right-center-button"
            widget: "object"
            summary: "{{fields.name}}"
            collapsed: true
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Link", name: "link", widget: "string", required: false }
              - label: "Contents"
                name: "contents"
                widget: 'list'
                fields:
                  - { label: Name, name: name, widget: string }
                  - { label: Link, name: link, widget: string }
          - label: "Far-right Navigation Button"
            name: "right-end-button"
            widget: "object"
            summary: "{{fields.name}}"
            collapsed: true
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Link", name: "link", widget: "string" }